// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// El CLI (migrate, generate, studio) usa esta URL. Va DIRECT_URL (conexion
// session/no pooleada) porque Migrate necesita locks de advisory que no
// funcionan de forma confiable atras del pooler en modo transaccion.
// El cliente en runtime (src/server/db.ts) usa DATABASE_URL (pooleada) por su cuenta,
// via el adapter de @prisma/adapter-pg, independiente de esta config.
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
